import os


ADDITIONAL_SKILLS = [
    # More specific APIs and services
    {"name": "stripe-api", "desc": "Stripe payment API", "tools": "Write, Read"},
    {"name": "paypal-api", "desc": "PayPal API", "tools": "Write, Read"},
    {"name": "braintree", "desc": "Braintree payments", "tools": "Write, Read"},
    {"name": "square-api", "desc": "Square API", "tools": "Write, Read"},
    {"name": "adyen", "desc": "Adyen payments", "tools": "Write, Read"},
    {"name": "plaid", "desc": "Plaid banking API", "tools": "Write, Read"},
    {"name": "twilio", "desc": "Twilio SMS/voice", "tools": "Write, Read"},
    {"name": "nexmo", "desc": "Nexmo Vonage", "tools": "Write, Read"},
    {"name": "sendgrid", "desc": "SendGrid email", "tools": "Write, Read"},
    {"name": "mailgun", "desc": "Mailgun email", "tools": "Write, Read"},
    {"name": "ses", "desc": "AWS SES email", "tools": "Write, Read"},
    {"name": "postmark", "desc": "Postmark email", "tools": "Write, Read"},
    {"name": "mandrill", "desc": "Mandrill email", "tools": "Write, Read"},
    {"name": "mailchimp", "desc": "Mailchimp marketing", "tools": "Write, Read"},
    {"name": "sendinblue", "desc": "SendinBlue", "tools": "Write, Read"},
    {"name": "hubspot", "desc": "HubSpot CRM", "tools": "Write, Read"},
    {"name": "salesforce", "desc": "Salesforce CRM", "tools": "Write, Read"},
    {"name": "zendesk", "desc": "Zendesk support", "tools": "Write, Read"},
    {"name": "intercom", "desc": "Intercom chat", "tools": "Write, Read"},
    {"name": "freshdesk", "desc": "Freshdesk", "tools": "Write, Read"},
    {"name": "drift", "desc": "Drift chat", "tools": "Write, Read"},
    {"name": "segment", "desc": "Segment analytics", "tools": "Write, Read"},
    {"name": "mixpanel", "desc": "Mixpanel analytics", "tools": "Write, Read"},
    {"name": "amplitude", "desc": "Amplitude analytics", "tools": "Write, Read"},
    {"name": "heap", "desc": "Heap analytics", "tools": "Write, Read"},
    {"name": "snowplow", "desc": "Snowplow analytics", "tools": "Write, Read"},
    {"name": "newrelic", "desc": "New Relic monitoring", "tools": "Write, Read"},
    {"name": "datadog", "desc": "Datadog monitoring", "tools": "Write, Read"},
    {"name": "sentry", "desc": "Sentry error tracking", "tools": "Write, Read"},
    {"name": "bugsnag", "desc": "Bugsnag errors", "tools": "Write, Read"},
    {"name": "rollbar", "desc": "Rollbar errors", "tools": "Write, Read"},
    {"name": "airbrake", "desc": "Airbrake errors", "tools": "Write, Read"},
    {"name": "honeybadger", "desc": "Honeybadger errors", "tools": "Write, Read"},
    {"name": "raygun", "desc": "Raygun errors", "tools": "Write, Read"},
    {"name": "logrocket", "desc": "LogRocket logs", "tools": "Write, Read"},
    {"name": " papertrail", "desc": "Papertrail logs", "tools": "Write, Read"},
    {"name": "sumologic", "desc": "Sumo Logic logs", "tools": "Write, Read"},
    {"name": "cloudwatch", "desc": "CloudWatch logs", "tools": "Write, Read"},
    {"name": "stackify", "desc": "Stackify logs", "tools": "Write, Read"},
    {"name": "logrus", "desc": "Logrus logging", "tools": "Write, Read"},
    {"name": "zerolog", "desc": "zerolog Go logging", "tools": "Write, Read"},
    {"name": "zapier", "desc": "Zapier automation", "tools": "Write, Read"},
    {"name": "ifttt", "desc": "IFTTT automation", "tools": "Write, Read"},
    {"name": "make", "desc": "Make automation", "tools": "Write, Read"},
    {"name": "integromat", "desc": "Integromat no-code", "tools": "Write, Read"},
    {"name": "n8n", "desc": "n8n workflow", "tools": "Write, Read"},
    {"name": "pipedream", "desc": "PipeDream", "tools": "Write, Read"},
    {"name": "webhooks", "desc": "Webhook automation", "tools": "Write, Read"},
    {"name": "zapier-cli", "desc": "Zapier CLI", "tools": "Write, Read"},

    # More languages
    {"name": "elm", "desc": "Elm programming", "tools": "Write, Read"},
    {"name": "purescript", "desc": "PureScript", "tools": "Write, Read"},
    {"name": "idris", "desc": "Idris programming", "tools": "Write, Read"},
    {"name": "agda", "desc": "Agda programming", "tools": "Write, Read"},
    {"name": "coq", "desc": "Coq proof assistant", "tools": "Write, Read"},
    {"name": "lean", "desc": "Lean theorem", "tools": "Write, Read"},
    {"name": "fstar", "desc": "F* verification", "tools": "Write, Read"},
    {"name": "rust-analyzer", "desc": "Rust analyzer", "tools": "Write, Read"},
    {"name": "clap-rs", "desc": "Clap CLI Rust", "tools": "Write, Read"},
    {"name": "tokio", "desc": "Tokio async Rust", "tools": "Write, Read"},
    {"name": "actix", "desc": "Actix web Rust", "tools": "Write, Read"},
    {"name": "warp", "desc": "Warp web Rust", "tools": "Write, Read"},
    {"name": "axum", "desc": "Axum web Rust", "tools": "Write, Read"},
    {"name": "rocket-rs", "desc": "Rocket web Rust", "tools": "Write, Read"},
    {"name": "iron", "desc": "Iron web Rust", "tools": "Write, Read"},
    {"name": "gotham", "desc": "Gotham Rust", "tools": "Write, Read"},
    {"name": "nicru", "desc": "Nickel Rust web", "tools": "Write, Read"},

    # More Python frameworks
    {"name": "requests", "desc": "Requests HTTP", "tools": "Write, Read"},
    {"name": "httpx", "desc": "HTTPX async HTTP", "tools": "Write, Read"},
    {"name": "aiohttp", "desc": "aiohttp async", "tools": "Write, Read"},
    {"name": "fast-http", "desc": "Fast HTTP", "tools": "Write, Read"},
    {"name": "urllib", "desc": "urllib stdlib", "tools": "Write, Read"},
    {"name": "tornado-http", "desc": "Tornado HTTP", "tools": "Write, Read"},
    {"name": "charset-normalizer", "desc": "charset normalizer", "tools": "Write, Read"},
    {"name": "beautifulsoup", "desc": "BeautifulSoup", "tools": "Write, Read"},
    {"name": "lxml", "desc": "lxml XML/HTML", "tools": "Write, Read"},
    {"name": "selectolax", "desc": "selectolax fast HTML", "tools": "Write, Read"},
    {"name": "parsel", "desc": "Parsel CSS selector", "tools": "Write, Read"},
    {"name": "cssselect", "desc": "cssselect", "tools": "Write, Read"},
    {"name": "tinycss2", "desc": "tinycss2 parser", "tools": "Write, Read"},
    {"name": "feedparser", "desc": "feedparser RSS/Atom", "tools": "Write, Read"},
    {"name": "s gmllib3k", "desc": "sgmllib3k HTML", "tools": "Write, Read"},
    {"name": "MarkupSafe", "desc": "MarkupSafe", "tools": "Write, Read"},
    {"name": "bleach", "desc": "bleach HTML sanitizer", "tools": "Write, Read"},
    {"name": "html5lib", "desc": "html5lib", "tools": "Write, Read"},
    {"name": "mistune", "desc": "mistune parser", "tools": "Write, Read"},
    {"name": "markdown-it-py", "desc": "markdown-it-py", "tools": "Write, Read"},
    {"name": "commonmark", "desc": "CommonMark parser", "tools": "Write, Read"},
    {"name": "pyyaml", "desc": "PyYAML", "tools": "Write, Read"},
    {"name": "toml", "desc": "toml parser", "tools": "Write, Read"},
    {"name": "tomli", "desc": "tomli parser", "tools": "Write, Read"},
    {"name": "python-toml", "desc": "python-toml", "tools": "Write, Read"},
    {"name": "toml-wizard", "desc": "tomlwiz", "tools": "Write, Read"},
    {"name": "pydantic", "desc": "Pydantic validation", "tools": "Write, Read"},
    {"name": "dataclass", "desc": "dataclasses", "tools": "Write, Read"},
    {"name": "attrs", "desc": "attrs library", "tools": "Write, Read"},
    {"name": "cattrs", "desc": "cattrs", "tools": "Write, Read"},
    {"name": "msgspec", "desc": "msgspec", "tools": "Write, Read"},
    {"name": "marshmallow", "desc": "marshmallow", "tools": "Write, Read"},
    {"name": "serpy", "desc": "serpy serialization", "tools": "Write, Read"},
    {"name": "orjson", "desc": "orjson fast JSON", "tools": "Write, Read"},
    {"name": "ujson", "desc": "ujson", "tools": "Write, Read"},
    {"name": "python-rapidjson", "desc": "python-rapidjson", "tools": "Write, Read"},
    {"name": "msgpack", "desc": "msgpack", "tools": "Write, Read"},
    {"name": "ciso8601", "desc": "ciso8601 datetime", "tools": "Write, Read"},
    {"name": "python-dateutil", "desc": "python-dateutil", "tools": "Write, Read"},
    {"name": "pytz", "desc": "pytz timezone", "tools": "Write, Read"},
    {"name": "zoneinfo", "desc": "zoneinfo", "tools": "Write, Read"},
    {"name": "arrow", "desc": "Arrow datetime", "tools": "Write, Read"},
    {"name": "delorean", "desc": "Delorean datetime", "tools": "Write, Read"},
    {"name": "moment", "desc": "moment Python", "tools": "Write, Read"},
    {"name": "hydra", "desc": "Hydra config", "tools": "Write, Read"},
    {"name": "omegaconf", "desc": "OmegaConf", "tools": "Write, Read"},
    {"name": "python-dotenv", "desc": "python-dotenv", "tools": "Write, Read"},
    {"name": "dynaconf", "desc": "Dynaconf", "tools": "Write, Read"},
    {"name": " environs", "desc": "environs", "tools": "Write, Read"},
    {"name": "python-constantly", "desc": "constantly", "tools": "Write, Read"},
    {"name": "twisted", "desc": "Twisted async", "tools": "Write, Read"},
    {"name": "autobahn", "desc": "Autobahn", "tools": "Write, Read"},
    {"name": "crossbar", "desc": "Crossbar", "tools": "Write, Read"},

    # More data science
    {"name": "numpy-ndarray", "desc": "NumPy arrays", "tools": "Write, Read"},
    {"name": "numpy-ufunc", "desc": "NumPy ufuncs", "tools": "Write, Read"},
    {"name": "numpy-math", "desc": "NumPy math", "tools": "Write, Read"},
    {"name": "numpy-linalg", "desc": "NumPy linalg", "tools": "Write, Read"},
    {"name": "numpy-random", "desc": "NumPy random", "tools": "Write, Read"},
    {"name": "numpy-fft", "desc": "NumPy FFT", "tools": "Write, Read"},
    {"name": "numpy-polynomial", "desc": "NumPy poly", "tools": "Write, Read"},
    {"name": "numpy-ma", "desc": "NumPy masked", "tools": "Write, Read"},
    {"name": "numpy-rec", "desc": "NumPy recarray", "tools": "Write, Read"},
    {"name": "pandas-series", "desc": "Pandas Series", "tools": "Write, Read"},
    {"name": "pandas-dataframe", "desc": "Pandas DataFrame", "tools": "Write, Read"},
    {"name": "pandas-groupby", "desc": "Pandas groupby", "tools": "Write, Read"},
    {"name": "pandas-merge", "desc": "Pandas merge", "tools": "Write, Read"},
    {"name": "pandas-join", "desc": "Pandas join", "tools": "Write, Read"},
    {"name": "pandas-concat", "desc": "Pandas concat", "tools": "Write, Read"},
    {"name": "pandas-resample", "desc": "Pandas resample", "tools": "Write, Read"},
    {"name": "pandas-pivot", "desc": "Pandas pivot", "tools": "Write, Read"},
    {"name": "pandas-crosstab", "desc": "Pandas crosstab", "tools": "Write, Read"},
    {"name": "pandas-rollling", "desc": "Pandas rolling", "tools": "Write, Read"},
    {"name": "pandas-ewm", "desc": "Pandas EWM", "tools": "Write, Read"},
    {"name": "pandas-apply", "desc": "Pandas apply", "tools": "Write, Read"},
    {"name": "pandas-transform", "desc": "Pandas transform", "tools": "Write, Read"},
    {"name": "scipy-stats", "desc": "SciPy stats", "tools": "Write, Read"},
    {"name": "scipy-optimize", "desc": "SciPy optimize", "tools": "Write, Read"},
    {"name": "scipy-integrate", "desc": "SciPy integrate", "tools": "Write, Read"},
    {"name": "scipy-fft", "desc": "SciPy FFT", "tools": "Write, Read"},
    {"name": "scipy-interpolate", "desc": "SciPy interpolate", "tools": "Write, Read"},
    {"name": "scipy-signal", "desc": "SciPy signal", "tools": "Write, Read"},
    {"name": "scipy-linalg", "desc": "SciPy linalg", "tools": "Write, Read"},
    {"name": "sklearn-linear", "desc": "sklearn linear models", "tools": "Write, Read"},
    {"name": "sklearn-tree", "desc": "sklearn decision trees", "tools": "Write, Read"},
    {"name": "sklearn-ensemble", "desc": "sklearn ensemble", "tools": "Write, Read"},
    {"name": "sklearn-naive-bayes", "desc": "sklearn Naive Bayes", "tools": "Write, Read"},
    {"name": "sklearn-svm", "desc": "sklearn SVM", "tools": "Write, Read"},
    {"name": "sklearn-neighbors", "desc": "sklearn neighbors", "tools": "Write, Read"},
    {"name": "sklearn-clustering", "desc": "sklearn clustering", "tools": "Write, Read"},
    {"name": "sklearn-decomposition", "desc": "sklearn decompose", "tools": "Write, Read"},
    {"name": "sklearn-preprocessing", "desc": "sklearn preprocessing", "tools": "Write, Read"},
    {"name": "sklearn-model-selection", "desc": "sklearn model selection", "tools": "Write, Read"},
    {"name": "sklearn-metrics", "desc": "sklearn metrics", "tools": "Write, Read"},
    {"name": "sklearn-pipeline", "desc": "sklearn pipeline", "tools": "Write, Read"},
    {"name": "xgboost", "desc": "XGBoost", "tools": "Write, Read"},
    {"name": "lightgbm", "desc": "LightGBM", "tools": "Write, Read"},
    {"name": "catboost", "desc": "CatBoost", "tools": "Write, Read"},
    {"name": "optuna", "desc": "Optuna optimization", "tools": "Write, Read"},
    {"name": "hyperopt", "desc": "Hyperopt", "tools": "Write, Read"},
    {"name": "ray-tune", "desc": "Ray Tune", "tools": "Write, Read"},
    {"name": "auto-sklearn", "desc": "Auto-sklearn", "tools": "Write, Read"},
    {"name": "auto-keras", "desc": "Auto-Keras", "tools": "Write, Read"},
    {"name": "fastai", "desc": "FastAI", "tools": "Write, Read"},
    {"name": "pytorch-lightning", "desc": "PyTorch Lightning", "tools": "Write, Read"},
    {"name": "ignite", "desc": "PyTorch Ignite", "tools": "Write, Read"},
    {"name": "catalyst", "desc": "Catalyst RL", "tools": "Write, Read"},
    {"name": "pytorch-geometric", "desc": "PyG", "tools": "Write, Read"},
    {"name": "pygmae", "desc": "PyG-MAEG", "tools": "Write, Read"},
    {"name": "torch-scatter", "desc": "torch-scatter", "tools": "Write, Read"},
    {"name": "torch-sparse", "desc": "torch-sparse", "tools": "Write, Read"},
    {"name": "torch-cluster", "desc": "torch-cluster", "tools": "Write, Read"},
    {"name": "torch-spline-conv", "desc": "torch-spline-conv", "tools": "Write, Read"},

    # More devops
    {"name": "bash-scripting", "desc": "Bash scripting", "tools": "Write, Bash"},
    {"name": "zsh-scripting", "desc": "Zsh scripting", "tools": "Write, Read"},
    {"name": "fish-scripting", "desc": "Fish scripting", "tools": "Write, Read"},
    {"name": "tmux", "desc": "Tmux terminal", "tools": "Write, Read"},
    {"name": "screen", "desc": "GNU Screen", "tools": "Write, Read"},
    {"name": "byobu", "desc": "Byobu terminal", "tools": "Write, Read"},
    {"name": "alacritty", "desc": "Alacritty terminal", "tools": "Write, Read"},
    {"name": "kitty", "desc": "Kitty terminal", "tools": "Write, Read"},
    {"name": "wezterm", "desc": "WezTerm terminal", "tools": "Write, Read"},
    {"name": "powershell-core", "desc": "PowerShell Core", "tools": "Write, Read"},
    {"name": "windows-terminal", "desc": "Windows Terminal", "tools": "Write, Read"},
    {"name": "iterm2", "desc": "iTerm2 Mac", "tools": "Write, Read"},
    {"name": "terminus", "desc": "Terminus plugin", "tools": "Write, Read"},
    {"name": "oh-my-zsh", "desc": "Oh My Zsh", "tools": "Write, Read"},
    {"name": "oh-my-bash", "desc": "Oh My Bash", "tools": "Write, Read"},
    {"name": "zinit", "desc": "Zinit plugin manager", "tools": "Write, Read"},
    {"name": "zplugin", "desc": "Zplugin", "tools": "Write, Read"},
    {"name": "antigen", "desc": "Antigen for Zsh", "tools": "Write, Read"},
    {"name": " prezto", "desc": "Prezto", "tools": "Write, Read"},
    {"name": "vim", "desc": "Vim editor", "tools": "Write, Read"},
    {"name": "neovim", "desc": "Neovim", "tools": "Write, Read"},
    {"name": "emacs", "desc": "Emacs editor", "tools": "Write, Read"},
    {"name": "spacemacs", "desc": "Spacemacs", "tools": "Write, Read"},
    {"name": "doom-emacs", "desc": "Doom Emacs", "tools": "Write, Read"},
    {"name": "vscode", "desc": "VS Code", "tools": "Write, Read"},
    {"name": "vscodium", "desc": "VSCodium", "tools": "Write, Read"},
    {"name": "cursor-editor", "desc": "Cursor AI editor", "tools": "Write, Read"},
    {"name": "windsurf", "desc": "Windsurf editor", "tools": "Write, Read"},
    {"name": "zed-editor", "desc": "Zed editor", "tools": "Write, Read"},
    {"name": "git", "desc": "Git VCS", "tools": "Bash, Read"},
    {"name": "github", "desc": "GitHub", "tools": "Write, Read"},
    {"name": "gitlab", "desc": "GitLab", "tools": "Write, Read"},
    {"name": "bitbucket", "desc": "Bitbucket", "tools": "Write, Read"},
    {"name": "gitea", "desc": "Gitea self-hosted", "tools": "Write, Read"},
    {"name": "gogs", "desc": "Gogs self-hosted", "tools": "Write, Read"},
    {"name": "sourcegraph", "desc": "Sourcegraph", "tools": "Write, Read"},

    # More databases
    {"name": "postgresql", "desc": "PostgreSQL", "tools": "Write, Read"},
    {"name": "postgis", "desc": "PostGIS spatial", "tools": "Write, Read"},
    {"name": "pgvector", "desc": "pgvector embeddings", "tools": "Write, Read"},
    {"name": "mysql", "desc": "MySQL", "tools": "Write, Read"},
    {"name": "mariadb", "desc": "MariaDB", "tools": "Write, Read"},
    {"name": "percona", "desc": "Percona DB", "tools": "Write, Read"},
    {"name": "aurora", "desc": "AWS Aurora", "tools": "Write, Read"},
    {"name": "rds-postgres", "desc": "AWS RDS Postgres", "tools": "Write, Read"},
    {"name": "rds-mysql", "desc": "AWS RDS MySQL", "tools": "Write, Read"},
    {"name": "cloud-sql", "desc": "GCP Cloud SQL", "tools": "Write, Read"},
    {"name": "azure-sql", "desc": "Azure SQL", "tools": "Write, Read"},
    {"name": "azure-database", "desc": "Azure Database", "tools": "Write, Read"},

    # More specific frameworks
    {"name": "playwright-python", "desc": "Playwright Python", "tools": "Write, Read"},
    {"name": "selenium", "desc": "Selenium Python", "tools": "Write, Read"},
    {"name": "splinter", "desc": "Splinter web testing", "tools": "Write, Read"},
    {"name": "mechanize", "desc": "Mechanize", "tools": "Write, Read"},
    {"name": "requests-html", "desc": "requests-html", "tools": "Write, Read"},
    {"name": "httparty", "desc": "httparty Ruby", "tools": "Write, Read"},
    {"name": "faraday", "desc": "Faraday Ruby", "tools": "Write, Read"},
    {"name": "rest-client", "desc": "rest-client", "tools": "Write, Read"},
    {"name": "dio", "desc": "Dio HTTP Dart", "tools": "Write, Read"},
    {"name": "http", "desc": "Go http", "tools": "Write, Read"},
    {"name": "reqwest", "desc": "reqwest Rust", "tools": "Write, Read"},
    {"name": "actix-web", "desc": "Actix-web", "tools": "Write, Read"},
    {"name": "gunicorn", "desc": "Gunicorn WSGI", "tools": "Write, Read"},
    {"name": "uwsgi", "desc": "uWSGI", "tools": "Write, Read"},
    {"name": "waitress", "desc": "Waitress WSGI", "tools": "Write, Read"},
    {"name": "bjoern", "desc": "bjoern WSGI", "tools": "Write, Read"},
    {"name": "meinheld", "desc": "meinheld", "tools": "Write, Read"},
    {"name": "chameleon", "desc": "Chameleon templating", "tools": "Write, Read"},
    {"name": "jinja2", "desc": "Jinja2 templating", "tools": "Write, Read"},
    {"name": "mako", "desc": "Mako templating", "tools": "Write, Read"},
    {"name": "cheetah", "desc": "Cheetah templating", "tools": "Write, Read"},
    {"name": "tornado-templating", "desc": "Tornado templating", "tools": "Write, Read"},
    {"name": "duct", "desc": "Duct Clojure", "tools": "Write, Read"},
    {"name": "luminus", "desc": "Luminus Clojure", "tools": "Write, Read"},
    {"name": "ring", "desc": "Ring Clojure", "tools": "Write, Read"},

    # Additional frameworks
    {"name": "htmx", "desc": "HTMX", "tools": "Write, Read"},
    {"name": "alpine-js", "desc": "Alpine.js", "tools": "Write, Read"},
    {"name": "livewire", "desc": "Livewire", "tools": "Write, Read"},
    {"name": "inertia", "desc": "Inertia.js", "tools": "Write, Read"},
    {"name": "filament", "desc": "Filament PHP", "tools": "Write, Read"},
    {"name": "yii", "desc": "Yii PHP", "tools": "Write, Read"},
    {"name": "cakephp", "desc": "CakePHP", "tools": "Write, Read"},
    {"name": "codeigniter", "desc": "CodeIgniter", "tools": "Write, Read"},
    {"name": "fuelphp", "desc": "FuelPHP", "tools": "Write, Read"},
    {"name": "slim", "desc": "Slim PHP", "tools": "Write, Read"},
    {"name": "lumen", "desc": "Lumen PHP", "tools": "Write, Read"},
    {"name": "silex", "desc": "Silex PHP", "tools": "Write, Read"},
    {"name": "phalcon", "desc": "Phalcon PHP", "tools": "Write, Read"},
    {"name": "kumbia", "desc": "KumbiaPHP", "tools": "Write, Read"},
    {"name": "phalpie", "desc": "Phalpie", "tools": "Write, Read"},

    # More frameworks
    {"name": "rails-api", "desc": "Rails API mode", "tools": "Write, Glob"},
    {"name": "grape", "desc": "Grape API Ruby", "tools": "Write, Read"},
    {"name": "pgdice", "desc": "Ruby pg", "tools": "Write, Read"},
    {"name": "sequel", "desc": "Sequel Ruby ORM", "tools": "Write, Read"},
    {"name": "rom", "desc": "ROM Ruby", "tools": "Write, Read"},
    {"name": "dry-rb", "desc": "dry-rb", "tools": "Write, Read"},
    {"name": "hanami", "desc": "Hanami Ruby", "tools": "Write, Read"},
    {"name": "rodak", "desc": "Rodakore", "tools": "Write, Read"},
    {"name": "nexus", "desc": "Nexus Ruby", "tools": "Write, Read"},

    # Even more
    {"name": "tapioca", "desc": "Tapioca Ruby", "tools": "Write, Read"},
    {"name": "graphql-ruby", "desc": "GraphQL Ruby", "tools": "Write, Read"},
    {"name": "apollo-client", "desc": "Apollo Client JS", "tools": "Write, Read"},
    {"name": "urql", "desc": "urql GraphQL", "tools": "Write, Read"},
    {"name": "prism-react-renderer", "desc": "Prism highlighter", "tools": "Write, Read"},
    {"name": "react-syntax-highlighter", "desc": "React syntax", "tools": "Write, Read"},
    {"name": "prismjs", "desc": "PrismJS", "tools": "Write, Read"},
    {"name": "highlight-js", "desc": "highlight.js", "tools": "Write, Read"},
    {"name": "shiki", "desc": "Shiki syntax", "tools": "Write, Read"},
    {"name": "pygments", "desc": "Pygments", "tools": "Write, Read"},

    # Additional
    {"name": "faker", "desc": "Faker data", "tools": "Write, Read"},
    {"name": "mimesis", "desc": "Mimesis data", "tools": "Write, Read"},
    {"name": "snowball", "desc": "Snowball stemmer", "tools": "Write, Read"},
    {"name": "nltk-stem", "desc": "NLTK stemmer", "tools": "Write, Read"},
    {"name": "wordnet", "desc": "WordNet", "tools": "Write, Read"},
    {"name": "stop-words", "desc": "Stop words", "tools": "Write, Read"},
    {"name": "porter-stemmer", "desc": "Porter stemmer", "tools": "Write, Read"},
    {"name": "snowball-stemmer", "desc": "Snowball stemmer", "tools": "Write, Read"},
    {"name": "word-segment", "desc": "Word segmentation", "tools": "Write, Read"},
    {"name": "phrase", "desc": "Phrase detection", "tools": "Write, Read"},

    # Even more frameworks
    {"name": "cftime", "desc": "cftime", "tools": "Write, Read"},
    {"name": "numpy-busday", "desc": "busday", "tools": "Write, Read"},
    {"name": "numpy-financial", "desc": "numpy-financial", "tools": "Write, Read"},
    {"name": "numpy-polynomial", "desc": "numpy-polynomial", "tools": "Write, Read"},
    {"name": "numpy-matrix", "desc": "numpy-matrix", "tools": "Write, Read"},
    {"name": "numpy-distutils", "desc": "numpy-distutils", "tools": "Write, Read"},
    {"name": "numpy-docstrings", "desc": "numpy-docstrings", "tools": "Write, Read"},
    {"name": "numpy-testing", "desc": "numpy-testing", "tools": "Write, Read"},
    {"name": "numpy-distributions", "desc": "numpy-distributions", "tools": "Write, Read"},
    {"name": "numpy-fft", "desc": "numpy-fft", "tools": "Write, Read"},
    {"name": "numpy-linalg", "desc": "numpy-linalg", "tools": "Write, Read"},
    {"name": "numpy-ma", "desc": "numpy-ma", "tools": "Write, Read"},
    {"name": "numpy-ma-testutils", "desc": "numpy-ma-testutils", "tools": "Write, Read"},
    {"name": "numpy-benchmark", "desc": "numpy-benchmark", "tools": "Write, Read"},
    {"name": "numpy-randomgen", "desc": "numpy-randomgen", "tools": "Write, Read"},

    # More specific tools
    {"name": "pytest-cov", "desc": "pytest-cov", "tools": "Write, Read"},
    {"name": "pytest-xdist", "desc": "pytest-xdist", "tools": "Write, Read"},
    {"name": "pytest-mock", "desc": "pytest-mock", "tools": "Write, Read"},
    {"name": "pytest-timeout", "desc": "pytest-timeout", "tools": "Write, Read"},
    {"name": "pytest-order", "desc": "pytest-order", "tools": "Write, Read"},
    {"name": "pytest-randomly", "desc": "pytest-randomly", "tools": "Write, Read"},
    {"name": "pytest-sugar", "desc": "pytest-sugar", "tools": "Write, Read"},
    {"name": "pytest-html", "desc": "pytest-html", "tools": "Write, Read"},
    {"name": "pytest-json-report", "desc": "pytest-json-report", "tools": "Write, Read"},
    {"name": "pytest-junit", "desc": "pytest-junit", "tools": "Write, Read"},
    {"name": "pytest-anyio", "desc": "pytest-anyio", "tools": "Write, Read"},
    {"name": "pytest-asyncio", "desc": "pytest-asyncio", "tools": "Write, Read"},
    {"name": "pytest-tornado", "desc": "pytest-tornado", "tools": "Write, Read"},
    {"name": "pytest-aiohttp", "desc": "pytest-aiohttp", "tools": "Write, Read"},
    {"name": "pytest-fast-api", "desc": "pytest-fast-api", "tools": "Write, Read"},
    {"name": "pytest-django", "desc": "pytest-django", "tools": "Write, Read"},
    {"name": "pytest-flask", "desc": "pytest-flask", "tools": "Write, Read"},
    {"name": "pytest-plugins", "desc": "pytest-plugins", "tools": "Write, Read"},
    {"name": "pytest-cmd", "desc": "pytest-cmd", "tools": "Write, Read"},
    {"name": "pytest-console-scripts", "desc": "pytest-console-scripts", "tools": "Write, Read"},
    {"name": "pytest-cases", "desc": "pytest-cases", "tools": "Write, Read"},
    {"name": "pytest-parameterize", "desc": "pytest-parameterize", "tools": "Write, Read"},
    {"name": "pytest-datadir", "desc": "pytest-datadir", "tools": "Write, Read"},
    {"name": "pytest-recording", "desc": "pytest-recording", "tools": "Write, Read"},
    {"name": "vcr-pytest", "desc": "vcr-pytest", "tools": "Write, Read"},
    {"name": "betamax", "desc": "Betamax", "tools": "Write, Read"},
    {"name": "responses", "desc": "responses library", "tools": "Write, Read"},
    {"name": "aioresponses", "desc": "aioresponses", "tools": "Write, Read"},
    {"name": "httpretty", "desc": "httpretty", "tools": "Write, Read"},
    {"name": "mock-requests", "desc": "mock-requests", "tools": "Write, Read"},
]


def add_more_skills():
    base_path = r"C:\Users\11vat\Desktop\Copilot\Aider-Local-llm-agent\agent-system\.claude\skills"
    
    existing_dirs = []
    if os.path.exists(base_path):
        existing_dirs = [d.name for d in os.scandir(base_path) if d.is_dir()]
    
    total = 0
    for skill in ADDITIONAL_SKILLS:
        skill_path = os.path.join(base_path, skill["name"])
        
        if skill["name"] in existing_dirs:
            continue
        
        os.makedirs(skill_path, exist_ok=True)
        
        skill_file = os.path.join(skill_path, "SKILL.md")
        
        content = f"""---
name: {skill['name']}
description: {skill['desc']} - use when working on related tasks
tools: {skill['tools']}
model: qwen2.5-coder:14b
---
# {skill['desc']}

## When to Use
Use this skill when working on {skill['desc'].lower()}.

## Guidelines
- Use appropriate tools
- Follow best practices
"""
        
        with open(skill_file, "w", encoding="utf-8") as f:
            f.write(content)
        
        total += 1
    
    all_dirs = []
    if os.path.exists(base_path):
        all_dirs = [d.name for d in os.scandir(base_path) if d.is_dir()]
    
    print(f"Added: {total}")
    print(f"Total: {len(all_dirs)}")
    return total


if __name__ == "__main__":
    add_more_skills()