"""Underspecification Handling — detecting and resolving ambiguity.

Inspired by the Ambig-SWE framework. Before executing, the system detects
underspecified goals, ambiguous requirements, and implicit assumptions,
then generates structured clarification dialogs.

This module provides:
- AmbiguityDetector: Analyzes goals/plans for underspecification
- ClarificationDialog: Structured Q&A sequences that resolve ambiguity
- AmbiguityType taxonomy: What kind of ambiguity was detected
- Resolution tracking: How ambiguity was resolved and by whom
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple
import re
import time


class AmbiguityType(Enum):
    """Taxonomy of ambiguity types found in software requirements."""
    SCOPE = "scope"                 # Unclear boundaries (which files? which functions?)
    BEHAVIOR = "behavior"           # Unclear expected behavior (what should happen?)
    CONSTRAINT = "constraint"       # Missing constraints (performance? compatibility?)
    NAMING = "naming"               # Ambiguous naming (which "config"? which "handler"?)
    DEPENDENCY = "dependency"       # Unclear dependencies (which version? which API?)
    ORDERING = "ordering"           # Unclear sequencing (before/after what?)
    ERROR_HANDLING = "error_handling"  # Missing error cases (what if X fails?)
    EDGE_CASE = "edge_case"         # Unspecified edge cases (empty input? null?)
    INTENT = "intent"               # Unclear purpose (why this change?)
    ALTERNATIVE = "alternative"     # Multiple valid approaches (which pattern?)


class ResolutionMethod(Enum):
    """How an ambiguity was resolved."""
    USER_ANSWER = "user_answer"     # Human answered the question
    DEFAULT = "default"             # Used sensible default (with notification)
    INFERRED = "inferred"           # Inferred from context/codebase
    DEFERRED = "deferred"           # Marked for later resolution
    SKIPPED = "skipped"             # User chose to skip


@dataclass
class AmbiguitySignal:
    """A detected ambiguity in a goal or plan.

    Signals are raw detections before they become clarification questions.
    """
    type: AmbiguityType = AmbiguityType.SCOPE
    description: str = ""
    source_text: str = ""       # The text that triggered detection
    confidence: float = 0.8     # How confident we are this is actually ambiguous
    suggested_question: str = ""
    suggested_options: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ClarificationQuestion:
    """A question to resolve an ambiguity."""
    id: str = ""
    question: str = ""
    ambiguity_type: AmbiguityType = AmbiguityType.SCOPE
    options: List[str] = field(default_factory=list)  # Suggested answers
    default: str = ""                     # Default if user skips
    context: str = ""                     # Why we're asking
    priority: int = 1                     # 1=must-answer, 2=should-answer, 3=nice-to-know
    answer: str = ""
    resolution: ResolutionMethod = ResolutionMethod.DEFERRED
    resolved_at: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def resolved(self) -> bool:
        return self.resolution != ResolutionMethod.DEFERRED

    def resolve(self, answer: str, method: ResolutionMethod = ResolutionMethod.USER_ANSWER) -> None:
        self.answer = answer
        self.resolution = method
        self.resolved_at = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id, "question": self.question,
            "ambiguity_type": self.ambiguity_type.value,
            "options": self.options, "default": self.default,
            "context": self.context, "priority": self.priority,
            "answer": self.answer, "resolution": self.resolution.value,
            "resolved_at": self.resolved_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ClarificationQuestion":
        return cls(
            id=data.get("id", ""),
            question=data.get("question", ""),
            ambiguity_type=AmbiguityType(data.get("ambiguity_type", "scope")),
            options=data.get("options", []),
            default=data.get("default", ""),
            context=data.get("context", ""),
            priority=data.get("priority", 1),
            answer=data.get("answer", ""),
            resolution=ResolutionMethod(data.get("resolution", "deferred")),
            resolved_at=data.get("resolved_at", 0.0),
        )


@dataclass
class ClarificationDialog:
    """A sequence of clarification questions for a goal/plan.

    Dialogs are generated by the AmbiguityDetector and presented to the
    user during the UNDERSTAND or DISCUSS phases of the cognitive loop.
    """
    id: str = ""
    goal: str = ""
    questions: List[ClarificationQuestion] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)

    @property
    def pending(self) -> List[ClarificationQuestion]:
        return [q for q in self.questions if not q.resolved]

    @property
    def answered(self) -> List[ClarificationQuestion]:
        return [q for q in self.questions if q.resolved]

    @property
    def all_resolved(self) -> bool:
        # Only priority 1 (must-answer) questions need resolution
        return all(q.resolved for q in self.questions if q.priority == 1)

    @property
    def must_answer(self) -> List[ClarificationQuestion]:
        return [q for q in self.questions if q.priority == 1 and not q.resolved]

    def resolve_with_defaults(self) -> int:
        """Resolve all unresolved questions with their defaults. Returns count."""
        count = 0
        for q in self.questions:
            if not q.resolved and q.default:
                q.resolve(q.default, ResolutionMethod.DEFAULT)
                count += 1
        return count

    def summary(self) -> str:
        total = len(self.questions)
        resolved = len(self.answered)
        pending = len(self.pending)
        must = len(self.must_answer)
        return (
            f"Clarification: {resolved}/{total} resolved, "
            f"{pending} pending ({must} must-answer)"
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id, "goal": self.goal,
            "questions": [q.to_dict() for q in self.questions],
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ClarificationDialog":
        return cls(
            id=data.get("id", ""),
            goal=data.get("goal", ""),
            questions=[ClarificationQuestion.from_dict(q) for q in data.get("questions", [])],
            created_at=data.get("created_at", time.time()),
        )


# ─── Ambiguity Detection ──────────────────────────────────────────

# Heuristic patterns that indicate ambiguity
_SCOPE_SIGNALS = [
    (r'\b(refactor|improve|fix|update|change|modify)\b', 0.6, "Which specific files/functions?"),
    (r'\b(the|this|that|it)\s+(code|function|module|class)\b', 0.5, "Which specific code entity?"),
    (r'\b(everything|all|entire|whole)\b', 0.7, "What's the scope boundary?"),
]

_BEHAVIOR_SIGNALS = [
    (r'\b(better|improve|enhance|optimize)\b', 0.6, "What does 'better' mean specifically?"),
    (r'\b(handle|manage|deal with)\s+(errors?|exceptions?)\b', 0.5, "Which error cases?"),
    (r'\b(should|could|might|may)\b', 0.4, "Is this a requirement or a suggestion?"),
]

_CONSTRAINT_SIGNALS = [
    (r'\b(fast|quick|efficient|performant)\b', 0.6, "What performance threshold?"),
    (r'\b(compatible|backward|legacy)\b', 0.5, "Which versions must be supported?"),
    (r'\b(secure|safe|protected)\b', 0.5, "What security requirements?"),
]

_EDGE_CASE_SIGNALS = [
    (r'\b(input|data|request)\b', 0.4, "What about empty/null/invalid input?"),
    (r'\b(concurrent|parallel|async)\b', 0.5, "What about race conditions?"),
    (r'\b(network|api|external)\b', 0.4, "What about timeouts/failures?"),
]

_ALL_SIGNAL_GROUPS: List[Tuple[AmbiguityType, list]] = [
    (AmbiguityType.SCOPE, _SCOPE_SIGNALS),
    (AmbiguityType.BEHAVIOR, _BEHAVIOR_SIGNALS),
    (AmbiguityType.CONSTRAINT, _CONSTRAINT_SIGNALS),
    (AmbiguityType.EDGE_CASE, _EDGE_CASE_SIGNALS),
]


class AmbiguityDetector:
    """Detects underspecification in goals and plans.

    Uses heuristic pattern matching as a first pass, with extensible
    rules for project-specific ambiguity detection.

    Usage:
        detector = AmbiguityDetector()

        # Detect ambiguities in a goal
        signals = detector.analyze("Improve the error handling in the auth module")
        # -> [AmbiguitySignal(type=BEHAVIOR, ...), AmbiguitySignal(type=SCOPE, ...)]

        # Generate a clarification dialog
        dialog = detector.generate_dialog(
            "Refactor the config system",
            signals=signals,
        )

        # Present to user and collect answers
        for q in dialog.must_answer:
            answer = await human.ask_user(q.question, context=q.context)
            q.resolve(answer)
    """

    def __init__(self):
        self._custom_rules: List[Callable] = []
        self._signal_groups = list(_ALL_SIGNAL_GROUPS)

    def add_rule(self, rule: Callable) -> None:
        """Add a custom detection rule.

        Rule signature: callable(text: str) -> List[AmbiguitySignal]
        """
        self._custom_rules.append(rule)

    def analyze(self, text: str, *,
                min_confidence: float = 0.4,
                context: Optional[Dict[str, Any]] = None) -> List[AmbiguitySignal]:
        """Analyze text for ambiguity signals.

        Args:
            text: The goal, plan step, or requirement text
            min_confidence: Minimum confidence to include
            context: Optional context (existing plan, codebase info)

        Returns:
            List of detected ambiguity signals
        """
        signals = []

        # Run heuristic patterns
        for ambiguity_type, patterns in self._signal_groups:
            for pattern, confidence, question in patterns:
                matches = list(re.finditer(pattern, text, re.IGNORECASE))
                if matches:
                    # Boost confidence if multiple matches
                    adj_confidence = min(1.0, confidence + 0.1 * (len(matches) - 1))
                    if adj_confidence >= min_confidence:
                        signals.append(AmbiguitySignal(
                            type=ambiguity_type,
                            description=f"Detected '{matches[0].group()}' — {question}",
                            source_text=text,
                            confidence=adj_confidence,
                            suggested_question=question,
                        ))

        # Run custom rules
        for rule in self._custom_rules:
            try:
                custom_signals = rule(text)
                signals.extend(s for s in custom_signals if s.confidence >= min_confidence)
            except Exception:
                pass  # Don't crash on bad custom rules

        # Deduplicate by type (keep highest confidence per type)
        seen_types = {}
        for s in signals:
            if s.type not in seen_types or s.confidence > seen_types[s.type].confidence:
                seen_types[s.type] = s

        return sorted(seen_types.values(), key=lambda s: s.confidence, reverse=True)

    def generate_dialog(self, goal: str, *,
                        signals: Optional[List[AmbiguitySignal]] = None,
                        max_questions: int = 5) -> ClarificationDialog:
        """Generate a clarification dialog from detected ambiguity.

        Args:
            goal: The original goal text
            signals: Pre-detected signals (if None, runs analyze())
            max_questions: Maximum questions to include

        Returns:
            ClarificationDialog ready for user interaction
        """
        import uuid
        if signals is None:
            signals = self.analyze(goal)

        dialog = ClarificationDialog(
            id=str(uuid.uuid4())[:10],
            goal=goal,
        )

        for i, signal in enumerate(signals[:max_questions]):
            priority = 1 if signal.confidence >= 0.7 else (2 if signal.confidence >= 0.5 else 3)
            dialog.questions.append(ClarificationQuestion(
                id=f"q-{i}",
                question=signal.suggested_question,
                ambiguity_type=signal.type,
                options=signal.suggested_options,
                context=signal.description,
                priority=priority,
            ))

        return dialog

    def quick_check(self, text: str) -> bool:
        """Quick check: does this text have any significant ambiguity?

        Returns True if there are any high-confidence signals.
        """
        signals = self.analyze(text, min_confidence=0.6)
        return len(signals) > 0
